---
title: "Second Try - Tony"
format: pdf
editor: visual
---

## Library Packages

```{r}
#| warning: false
#| message: false 
library(forecast)
library(tidyverse)
library(ggplot2)
```

## Use different models to try

For the second try, we will try to use covariates

1.  let's try ARIMA with Fourier terms

```{r}
#| echo: false

plot(ts_load)
# calculate the foureir terms first
foureir_term <- ts_combined[, 1] %>% 
  fourier(K = c(2, 12))

# combine foureir terms with humidity and temperature
covariates <- ts_combined[, c(2:3)] %>% 
  cbind(foureir_term)

covariates_train <- covariates %>% subset(end = 2191-365)
covariates_test <- covariates %>% subset(start = 2191-365+1)
# model with autoarima and covariates
arima.four.cov <- ts_load_train %>% 
  auto.arima(xreg = covariates_train, seasonal = FALSE)

# forecast 2010 with autoarima
forecast.arima.four.cov <- forecast(arima.four.cov,
                                    h = 365, 
                                    xreg = covariates_test)

# calculate its accuracy
performance.arima.four.cov <- accuracy(forecast.arima.four.cov$mean,
                                       ts_load_test
                                       )
```

2.  try STL models with fourier terms and covariates

```{r}
stl.four.cov <- stlm(ts_load_train,
                    s.window = "periodic",
                    method = "arima",
                    xreg = covariates_train)

forecast.stl.four.cov <- forecast(stl.four.cov,
                                  h = 365,
                                  xreg = covariates_test)

performance.stl.four.cov <- accuracy(ts_load_test, forecast.stl.four.cov$mean)
```

3.  try neural network with covariate

    ```{r}
    nn.cov_31 <- ts_load_train %>% 
      nnetar(p = 3, P = 1, xreg = covariates_train)

    nn.cov_30 <- ts_load_train %>% 
      nnetar(p = 3, P = 0, xreg = covariates_train)

    nn.cov_21 <- ts_load_train %>% 
      nnetar(p = 2, P = 1, xreg = covariates_train)

    # try to use repeats 
    nn.cov_21_30 <- ts_load_train %>% 
      nnetar(p = 2, P = 1, repeats = 30, xreg = covariates_train)



    for (i in seq(20, 50, by = 2)){
      nn.cov_21_repeats <- ts_load_train %>% 
      nnetar(p = 2, P = 1, repeats = i, xreg = covariates_train)
      
      fore.nn.cov_21_repeats <- nn.cov_21_repeats %>% 
        forecast(h = 365, xreg = covariates_test)
      
      nn.cov.score_21_repeats <- accuracy(fore.nn.cov_21_repeats$mean, ts_load_test)
      
      nn_scores <- nn_scores %>% 
        rbind(nn.cov.score_21_repeats)
    }

    fore.nn.cov_31 <- nn.cov_31 %>% forecast(h = 365, xreg = covariates_test)
    fore.nn.cov_30 <- nn.cov_30 %>% forecast(h = 365, xreg = covariates_test)
    fore.nn.cov_21 <- nn.cov_21 %>% forecast(h = 365, xreg = covariates_test)
    fore.nn.cov_21_30 <- nn.cov_21_30 %>% forecast(h = 365, xreg = covariates_test)

    nn.cov.score_31 <- accuracy(fore.nn.cov_31$mean, ts_load_test)
    nn.cov.score_30 <- accuracy(fore.nn.cov_30$mean, ts_load_test)
    nn.cov.score_21 <- accuracy(fore.nn.cov_21$mean, ts_load_test)
    nn.cov.score_21_30 <- accuracy(fore.nn.cov_21_30$mean, ts_load_test)

    nn_scores <- nn.cov.score_31 %>% 
      rbind(nn.cov.score_30, nn.cov.score_21, nn.cov.score_21_30)

    row.names(nn_scores) <- c("31", "30", "21", "21+30")

    ```

4.  TBATS model

```{r}

tbats.cov <- tbats(ts_load_train)

fore.tbats.cov <- tbats.cov %>% 
  forecast(h = 365)

# performance
tbats_score <- accuracy(fore.tbats.cov$mean, ts_load_test)
```

## Compare model performance

```{r}
scores_try2 <- performance.stl.four.cov %>% 
  rbind(performance.arima.four.cov, nn.cov.score_30, nn.cov.score_21, tbats_score)

row.names(scores_try2) <- c("STL with Fourier and Covariates",
                            "SARIMA with Fourier and Covariates",
                            "Neural Network 30",
                            "Neural Network 21",
                            "TBATS")

best_model_index <- which.min(scores_try2[,"RMSE"])
cat("The best model by RMSE is:", row.names(scores_try2[best_model_index,]))   
```

## Model and Forecast Covariates

```{r}

# graph two covariates
plot(ts_combined[, 2:3])
  # strong seasonality

# retrieve coviariates
ts_covariates <- ts_combined[, 2:3] %>% 
  ts(frequency = 365.25, start = c(2005, 1, 1))

ts_cov_train <- ts_covariates %>% subset(end = 2191-365)
ts_cov_test <- ts_covariates %>% subset(start = 2191-365+1)
# use SARIMA with fourier and stl+ets model humidity and check which one has the best performance

## SARIMA
sarima_hum_model <- auto.arima(ts_cov_train[, 1], 
                               seasonal = FALSE,
                               xreg = fourier(ts_cov_train[, 1],
                                              K = 7))
sarima_hum_perf <- sarima_hum_model %>% 
  forecast(h = 365,
           xreg = fourier(ts_cov_train[, 1], 
                          K = 7, 
                          h = 365)
           )

sarima_hum_score <- accuracy(sarima_hum_perf$mean, ts_cov_test[, 1])

## stl+ets 
stl_hum_perf <- stlm(ts_cov_train[, 1], h = 365,
                     xreg = fourier( ts_cov_train[, 1],
                                     K = 7,
                                     h = 365)
)
                     

stl_hum_score <- accuracy(stl_hum_perf$mean, ts_cov_test[, 1])

## tbats

tbats_hum_model <- tbats(ts_cov_train[, 1])

tbats_hum_perf <- forecast(tbats_hum_model, h = 365)

tbats_hum_score <- accuracy(tbats_hum_perf$mean, ts_cov_test[, 1])

## find the best model for humidity
humidity_scores <- rbind(sarima_hum_score, stl_hum_score)
row.names(humidity_scores) <- c("SARIMA", "STL")

humidity_scores
  # SARIMA is better for humidity

# use SARIMA with fourier and stl+ets model temperature and check which one has the best performance

## SARIMA
sarima_tem_model <- auto.arima(ts_cov_train[, 2], 
                               xreg = fourier(ts_cov_train[, 2],
                                              K = 7))
sarima_tem_perf <- sarima_tem_model %>% 
  forecast(h = 365,
           xreg = fourier(ts_cov_train[, 2], 
                          K = 7, 
                          h = 365)
           )

sarima_tem_score <- accuracy(sarima_tem_perf$mean, ts_cov_test[, 2])

## stl+ets 
stl_tem_perf <- stlf(ts_cov_train[, 2], h = 365)

stl_tem_score <- accuracy(stl_tem_perf$mean, ts_cov_test[, 2])

temperature_scores <- rbind(sarima_tem_score, stl_tem_score)
row.names(temperature_scores) <- c("SARIMA", "STL")

temperature_scores

# SARIMA is better

```

## Forecast Covariates

```{r}
# forecast temperature
tem_fore <- ts_covariates[,2] %>% 
  auto.arima(xreg = fourier(ts_covariates[,2],
                            K = 7)
             ) %>% 
  forecast(h = 59, 
           xreg = fourier(ts_covariates[,2],
                          K = 7,
                          h =59)
           )

# forecast humidity
hum_fore <- ts_covariates[,1] %>% 
  auto.arima(xreg = fourier(ts_covariates[,1],
                            K = 7)
             ) %>% 
  forecast(h = 59, 
           xreg = fourier(ts_covariates[,1],
                          K = 7,
                          h =59)
           )

# predict fourier terms 
future_fourier <- fourier(ts_load, K = c(2, 12), h = 59)

cov_fore <- cbind(hum_fore$mean, tem_fore$mean, future_fourier)
str(cov_fore)
```

## Forecast with Neural Network with Covariates

```{r}
# covariates
fourier_full <- fourier(ts_load, K = c(2, 12))
cov_full <- cbind(ts_combined[,2:3], fourier_full)

# predict! 
nn_four_cov_2011 <- ts_load %>% 
  nnetar(p = 2, P = 1, xreg = cov_full) %>% 
  forecast(h = 59,
           xreg = cov_fore)

# save results 
write.csv(nn_four_cov_2011$mean, "./Output/nn_model.csv", row.names = FALSE)

```

## 
